[package]
authors = ["Sebastian Nowicki <sebnow@gmail.com>"]
name = "adventofcode201719"
version = "0.1.0"
[[bin]]
name = "adventofcode201719"
path = "src/bin.rs"

[dependencies]
failure = "0.1.1"

[lib]
name = "adventofcode201719"
path = "src/lib.rs"
