[package]
name = "aocutil"
version = "0.1.0"
authors = ["Sebastian Nowicki <sebnow@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "^0.2.10"
termion = "^1.5.0"
anyhow = "^1.0.25"
euclid = "^0.22.1"
