[package]
name = "adventofcode201716"
version = "0.1.0"
authors = ["Sebastian Nowicki <sebnow@gmail.com>"]

[lib]
name = "adventofcode201716"
path = "src/lib.rs"

[[bin]]
name = "adventofcode201716"
path = "src/bin.rs"

[dependencies]
